/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sogilis.katalog.romanNumerals;

public class App {
    public static Integer convert(String input) {
        if (!input.isEmpty()) {
            return input.length();
        }
        return null;
    }
}
